### ISSUE TITLE
デザイン

### ISSUE THREAD

**Issue by syoshi** [syoshitest/textrepo#1]
TOPページに置こうと思っている各メニューとWORKS画像を2パターン作って比較したいと思います。

# TODO

- [ ] パターンA
- [ ] パターンB

**Comment by syoshi** [comment]
コメントができます。

**Comment by s02yoshi** [comment]
マークダウンは**Preview**タグで確認できます。

**Comment by syoshi** [comment]
このように掲示板に書き込むように簡単にコメントのやりとりができます。
